application: esoteric-storm-145212
version: v1
runtime: go
api_version: go1
threadsafe: yes

default_expiration: '0h'

handlers:

  - url: /favicon\.ico
    static_files: favicon\.ico
    upload: favicon.ico

  # - url: /scripts/(.*\.js)
  #   mime_type: text/javascript
  #   static_files: dist/scripts/\1
  #   upload: dist/scripts/(.*\.js)

  # - url: /?styles/(.*\.css)
  #   mime_type: text/javascript
  #   static_files: dist/styles/\1
  #   upload: dist/styles/(.*\.js)

  - url: /scripts
    static_dir: dist/scripts

  - url: /styles
    static_dir: dist/styles

  - url: /images
    static_dir: images

  - url: /$
    mime_type: text/html
    static_files: dist/index.html
    upload: dist/index.html

  - url: /.*
    script: _go_app

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - (.*).sass$
  # this is just here to speed up the deploy process, for now
  - ^images/(.*)
  ## remove this file
  - ^images/images\.list$
